# Generated by Django 5.0.1 on 2024-02-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('company_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gpt_comment', models.TextField(blank=True, null=True)),
                ('sentiment_analysis_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'company_info',
                'managed': False,
            },
        ),
    ]
