# Generated by Django 5.0.1 on 2024-02-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpInfo',
            fields=[
                ('corp_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('corp_name', models.CharField(max_length=50)),
                ('stock_code', models.CharField(blank=True, max_length=6, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('gpt_comment', models.TextField(blank=True, null=True)),
                ('sentiment_analysis_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'corp_info',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
    ]
