# Generated by Django 5.0.1 on 2024-02-22 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_top500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Top500',
        ),
    ]
